apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "url-shortener.componentName" (dict "root" $ "component" "api") }}
  labels:
    {{- include "url-shortener.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
data:
  REDIS_HOST: {{ include "url-shortener.componentName" (dict "root" $ "component" "redis") | quote }}
  REDIS_PORT: "6379"
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
